### ISSUE TITLE
Can we leverage apache arrow as a language-independent internal memory representation?

### ISSUE THREAD

**Issue by npuichigo** [facebookresearch/spdl#269]

**Comment by mthrok** [comment]
Hi

I'm not sure what "language-independent" means, but if you are using Arrow to represent a dataset, then you can pass an iterator to source and it just works.

I'm looking into a way to leverage Arrow or Pandas as a representation of dataset for specific use case but SPDL itself needs no change for that.

**Comment by npuichigo** [comment]
Thanks for your reply. I'm not sure the central representation of using SPDL, maybe the utilities provided by SPDL. I found the C++ code uses something like `Buffer`, `CudaStorage` and `Tensor`, so I asked the question if we can leverage zero-copy Arrow as an universal in-memory representation.

**Comment by mthrok** [comment]
I see. The data structure in C++ code serves different purpose than Dataframe and alike. 

The custom structure is just a wrapper around data structure of underlying IO processing library (FFmpeg). It's introduced to minimize the data copy while making the composition flexible. (And also to be independent of particular deep learning framework like PyTorch or JAX, yet compatible with them.) they are only used in spdl.io module, and this entire module is completely independent from spdl.dataloader module.

Data structure like Arrow is used to deal with multiple data points as a set (aka dataset), and so far, SPDL's Pipeline abstraction does not have particular relation ship with such format, because as I mentioned previously, SPDL's Pipeline cares if the input is [async] iterator or not, and the rest of the stages are just callable. If you convert Arrow, Pandas Dataframe, SQLite Database or anything to iterable, that's how SPDL understands the assignment.

Now, we are discussing adding high-level API that looks more like DataLoader class from PyTorch, built on top of the existing APIs. (Imagine like ImageNet dataset from torchvision but dataloader not dataset) That's where the choice of dataset representation, and there will be pros and cons for choosing one. So far I don't have much opinion (though I have slight preference SQLite3 because it won't require any additional dependency). If you have particular technical reasons that Arrow is preferred, I'm interested to listen to them.

**Comment by mthrok** [comment]
We now have an Meta-internal usecase where PyArrow Table is wrapped and used as a source of pipeline. It works fine without any modification to the source code.

One caveat is that PyArrow does not directly support row-by-row iteration, so it needs an extra step of extracting rows, and this is somewhat performance-sensitive.

One way to do this is to use sampler, and fetch multiple indices from sampler first, then extract rows. The following code snippet illustrates this idea.

```python
def iter_arrow_table(table, sampler) -> Iterator[dict[str, Any]]:
    for indices in itertools.batched(sampler, 1000):
        yield from table.take(indices).to_pylist()
```

Since SPDL is generic and I don't see a specific needs to add such tiny function in the library (which is not connected to the rest of the library), so I consider this is supported, and I will close this issue.

@npuichigo  Thanks for the question and suggestion. Feel free to follow-up.
